### PR TITLE
832204119 - TASK3

### PR DESCRIPTION
**Pull request by eouhen**

### CODE REVIEW

**Comment by SYguanxin** [comment]
下次交到collection-ai这个仓库

**Comment by eouhen** [comment]
那我现在要再交一次嘛



发自我的iPhone


------------------ Original ------------------
From: SYguanxin ***@***.***&gt;
Date: Sun, Dec 3, 2023 10:17 PM
To: west2-online-reserve/collection-python ***@***.***&gt;
Cc: AnnieHathaway ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [west2-online-reserve/collection-python] 832204119 - TASK3 (PR#74)





 
下次交到collection-ai这个仓库

**Comment by SYguanxin** [comment]
这次没事，下次别发这里了

**Comment by eouhen** [comment]
好滴~



发自我的iPhone


------------------ Original ------------------
From: SYguanxin ***@***.***&gt;
Date: Sun, Dec 3, 2023 10:20 PM
To: west2-online-reserve/collection-python ***@***.***&gt;
Cc: AnnieHathaway ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [west2-online-reserve/collection-python] 832204119 - TASK3 (PR#74)

**Review by SYguanxin — COMMENTED** [review]
写得不错

**Pull request closed without merging**
